Add support for `-file-prefix-map`
apple/swift-driver pull request #1076
Opened 2022-04-22 18:36 UTC by DavidGoldman

Swift-driver support for the flag being added in https://github.com/apple/swift/pull/42394

2022-05-13 14:20 UTC, allevato commented
@swift-ci please test

2022-05-16 22:48 UTC, bnbarham commented
Seems okay to me. @nkcsgexi could you take a look as well?

2022-05-16 23:02 UTC, artemcm commented on Sources/SwiftOptions/Options.swift
> +  public static let filePrefixMap: Option = Option("-file-prefix-map", .separate, attributes: [.frontend], metaVar: "<prefix=replacement>", helpText: "Remap source paths in debug, coverage, and index
Was this added following the process here:
https://github.com/apple/swift-driver#rebuilding-optionsswift
?

2022-05-16 23:04 UTC, artemcm commented
Please add a test that a driver invocation with `-file-prefix-map` propagates the option to `swift-frontend` invocations when needed. And maybe one to exercise `.error_opt_invalid_mappin`?

2022-05-16 23:05 UTC, artemcm approved these changes

2022-05-16 23:18 UTC, nkcsgexi requested changes
Please add tests for (1) passing down multiple -file-prefix-map, and (2) rejecting when the options is malformed.

2022-05-17 15:00 UTC, DavidGoldman commented on Sources/SwiftOptions/Options.swift
> +  public static let filePrefixMap: Option = Option("-file-prefix-map", .separate, attributes: [.frontend], metaVar: "<prefix=replacement>", helpText: "Remap source paths in debug, coverage, and index
Nope. I'm able to rerun this, but I'm seeing other unrelated changes that are outside the scope of this PR. WDYT?

2022-05-17 17:01 UTC, DavidGoldman commented on Sources/SwiftOptions/Options.swift
> +  public static let filePrefixMap: Option = Option("-file-prefix-map", .separate, attributes: [.frontend], metaVar: "<prefix=replacement>", helpText: "Remap source paths in debug, coverage, and index
OK, I've fixed the ordering of my flag here but I'd like to avoid other changes in this PR since I'd like to cherry pick it to Swift 5.7. I can send another PR to update these though.

2022-05-17 17:02 UTC, DavidGoldman commented
> Please add tests for (1) passing down multiple -file-prefix-map, and (2) rejecting when the options is malformed.

Done.

2022-05-17 19:36 UTC, allevato commented
@swift-ci please test

2022-05-19 23:39 UTC, DavidGoldman commented
Friendly ping @nkcsgexi, please take another look when you get a chance. Thanks

2022-05-19 23:44 UTC, nkcsgexi approved these changes
LGTM, Thank you!

2022-05-20 18:40 UTC, DavidGoldman commented
I don't have merge access, can someone else please merge this for me? Thanks!

2022-05-20 18:41 UTC, merged