Re-run makeOptions to sync up Swift and C++ driver
apple/swift-driver pull request #1134
Opened 2022-07-11 22:16 UTC by bnbarham

There's been a few PRs mentioning that running `makeOptions` results in
more churn than the one option they were expecting. Run separately to
sync up again.

2022-07-11 22:17 UTC, bnbarham commented
@swift-ci please test

2022-07-11 22:27 UTC, artemcm approved these changes

2022-07-11 22:36 UTC, bnbarham commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> +    try commandLine.appendLast(.enableExperimentalCxxInterop, from: &parsedOptions)
I'm a little confused about this @zoecarver. The Swift driver is currently passing `-enable-cxx-interop` to the frontend, but it should be `-enable-experimental-cxx-interop`... so how is this working at all 🤔?

2022-07-11 23:05 UTC, bnbarham commented
@swift-ci please test

2022-07-11 23:31 UTC, bnbarham commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> -    }
Also worth noting that there's a specific test for `-enable-experimental-cxx-interop` as a driver option.

2022-07-13 16:36 UTC, zoecarver commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> -    }
> currently we just have a -enable-experimental-cxx-interop frontend option only. Is that correct?

Yes, we should only have the frontend option, and it should be called `enable-experimental-cxx-interop` _not_ `enable-cxx-interop`.

2022-07-13 16:36 UTC, zoecarver approved these changes

2022-07-13 17:05 UTC, bnbarham commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> -    }
Thanks!

2022-07-15 20:17 UTC, bnbarham commented
@swift-ci please test

2022-07-15 20:22 UTC, bnbarham commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> -    // On Darwin, we only support libc++.
(And speaking of, that should also be removed from the C++ side)

2022-07-15 23:24 UTC, bnbarham commented
@swift-ci please test

2022-07-15 23:26 UTC, bnbarham commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> +      XCTAssertTrue(job.tool.name.hasSuffix(executableName("clang")))
@compnerd any thoughts on what this should be doing now? It doesn't seem to make sense to change linker options depending on swift-frontend flags, but that would seem to suggest that this *should* be a driver option rather than a frontend.

2022-07-15 23:32 UTC, compnerd commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> +      XCTAssertTrue(job.tool.name.hasSuffix(executableName("clang")))
This definitely is not correct - `clang++` must be used as the linker driver because that changes the linked library set.  I would say that if you must, promote `-enable-experimental-cxx-interop` to a driver flag, but this must remain as `clang++`.

2022-07-15 23:33 UTC, compnerd requested changes
This is going to break c++ interop on Windows.

2022-07-15 23:35 UTC, artemcm commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> +      XCTAssertTrue(job.tool.name.hasSuffix(executableName("clang")))
@zoecarver if we want to preserve this behavior, we need to bring back the driver flag.

2022-07-25 22:46 UTC, bnbarham commented
@swift-ci please test

2022-07-26 16:16 UTC, compnerd approved these changes

2022-07-26 16:17 UTC, bnbarham commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> +      XCTAssertTrue(job.tool.name.hasSuffix(executableName("clang")))
I moved it back to a driver option in swift.

2022-07-26 16:18 UTC, merged