Replace Foundation.Date with TimePoint
apple/swift-driver pull request #1171
Opened 2022-09-07 02:24 UTC by CodaFi

A TimePoint functions like a Duration, but for products that cannot yet use the niceties in Swift 5.7 like the Swift driver. This type carries a 64-bit second value and a 32-bit nanosecond value. Like Duration, it does not represent any one OS clock value, but is rather just a "point in time".

Using this type, we can simplify and clean up quite a few places that were trafficking in Foundation.Date and prepare for a future world where we have Duration too. The driver uses time point values to compare file modification times to each other - hence why we can get away with ignoring the epoch. The one oddity is the build record, which serializes time point values. But build records, like the rest of the incremental state, are not actually meant to leave a given user's machine.

2022-09-07 02:24 UTC, CodaFi commented
@swift-ci test

2022-09-07 02:35 UTC, CodaFi commented
@swift-ci test

2022-09-07 02:55 UTC, CodaFi commented
@swift-ci test

2022-09-07 03:04 UTC, CodaFi commented
@swift-ci test Windows

2022-09-07 14:13 UTC, artemcm approved these changes
Fantastic, thank you!

2022-09-07 16:16 UTC, compnerd commented on Sources/SwiftDriver/Utilities/DateAdditions.swift
> +                    nanoseconds: nanos)
nit: alignment seems odd

2022-09-07 16:16 UTC, compnerd commented on Sources/SwiftDriver/Utilities/DateAdditions.swift
> +    // Windows ticks in 100 nanosecond intervals.
This makes me think that you intended to use `GetSystemTimePreciseAsFileTime` rather than `GetSystemTime` and converting that to a `FILEITME`.

2022-09-07 16:44 UTC, CodaFi commented on Sources/SwiftDriver/Utilities/DateAdditions.swift
> +    // Windows ticks in 100 nanosecond intervals.
Great idea! I cribbed this from CF - perhaps they ought to look into using this same API, though TimeInterval isn't exactly a useful type when you start talking about <1us resolution precision.

2022-09-07 16:44 UTC, compnerd commented on Sources/SwiftDriver/Utilities/DateAdditions.swift
> +    return .seconds(result / 10_000_000)
This seems to need an explicit conversion ...
```suggestion
    return .seconds(Int(result / UInt64(10_000_000)))
```

2022-09-07 16:45 UTC, compnerd commented on Sources/SwiftDriver/Utilities/DateAdditions.swift
> +    // Windows ticks in 100 nanosecond intervals.
Yeah, CF, dispatch, Swift, everyone has a slightly different implementation.  There is a slight cost associated with the higher precision which is why it isn't as pervasively used.

2022-09-07 16:48 UTC, CodaFi commented
@swift-ci test

2022-09-07 16:49 UTC, compnerd commented
Eek; this seems to regress the test suite pretty badly:

```
Executed 1 test, with 34 failures (0 unexpected) in 129.017 (129.017) seconds
```

2022-09-07 16:54 UTC, owenv approved these changes

2022-09-07 16:54 UTC, compnerd requested changes
Seems to regress WIndows

2022-09-07 17:22 UTC, CodaFi commented
My bad, I need to correct for the Windows epoch difference in the file modification time function.

2022-09-07 22:56 UTC, CodaFi commented
@swift-ci test

2022-09-07 22:56 UTC, CodaFi commented
@swift-ci test Windows

2022-09-07 22:57 UTC, CodaFi commented
@swift-ci test Windows

2022-09-07 23:22 UTC, compnerd approved these changes
Thanks, this seems to resolve the Windows issues.

2022-09-08 01:25 UTC, CodaFi commented
apple/swift-package-manager#5759

@swift-ci test

2022-09-08 22:05 UTC, merged

2022-09-12 14:19 UTC, buttaface commented on Sources/SwiftDriver/Utilities/DateAdditions.swift
> +    return .seconds(64_092_211_200)
@CodaFi, it appears this line [broke building this repo for armv7](https://github.com/buttaface/swift-android-sdk/runs/8302044832?check_suite_focus=true#step:6:7000), because `seconds(value:)` takes an `Int` above:
```
swift-driver/Sources/SwiftDriver/Utilities/DateAdditions.swift:126:21: error: integer literal '64092211200' overflows when stored into 'Int'
    return .seconds(64_092_211_200)
```
Maybe it should take an explicit `Int64` instead?