Remove the use of hard-coded `.exe` suffix
apple/swift-driver pull request #1187
Opened 2022-09-16 17:45 UTC by stevapple

Additionally:
- Clarify that `lookup(executable:)` expects the argument without executable suffix.
- Update `executableName(_:)` to make it more native on Windows.

Fixes #1186

2022-09-16 18:06 UTC, compnerd approved these changes
Assuming that this does not regress the test suite on Windows, this seems reasonable to me with the additional comment request.  Unfortunately, the CI does not currently run the test suite on Windows and that will need to be run locally.

2022-09-16 18:06 UTC, compnerd commented on Sources/SwiftDriver/Driver/WindowsExtensions.swift
> +  }
I don't really understand this change.  Why is the `.` special case needed?  This seems worthy of a comment.

2022-09-16 18:17 UTC, stevapple commented on Sources/SwiftDriver/Driver/WindowsExtensions.swift
> +  }
This is identical to Windows’s behavior of always respecting files with explicit blank extension, but I also wonder if it’s necessary (given such use case is not suggested and really rare). Should we just drop the change or change into an `assert`?

2022-09-16 19:15 UTC, compnerd commented on Sources/SwiftDriver/Driver/WindowsExtensions.swift
> +  }
Yeah, I'm not sure if I see it as being necessary either.  I think that I would be okay with dropping the change.  If we need to, we can always add this in later with an explanation of why we ended up needing it.

2022-09-17 15:44 UTC, compnerd approved these changes

2022-09-17 15:45 UTC, compnerd commented
@swift-ci please test

2022-09-17 15:46 UTC, compnerd commented
Please provide the results from a local test run as the CI won't run the test suite on Windows.  We should ensure that the test suite isn't regressing on Windows due to this change prior to merging.

2022-09-17 16:42 UTC, stevapple commented
> Please provide the results from a local test run as the CI won't run the test suite on Windows. We should ensure that the test suite isn't regressing on Windows due to this change prior to merging.

Well, that’s something beyond my scope — as I mentioned before, Swift Driver test suite crashes silently on my machines. If you know how to deal with such problem, I’m glad that you can help.

![0306073F-4710-42DD-87E4-AA6ECD61977F](https://user-images.githubusercontent.com/26525394/190866481-112c610f-df13-430d-aa7d-571983654c73.png)
![截屏2022-09-18 00 39 53](https://user-images.githubusercontent.com/26525394/190867387-4c817f37-5119-4e1a-a279-d9aac87ae81a.png)

2022-09-17 19:39 UTC, compnerd commented
0xc00000fd means STATUS_STACK_OVERFLOW.  There is likely an infinite recursion going on but can't tell from just the screenshot what is going on.  I would say step through the assembly and find where the recursion starts and with what parameters, perhaps we can isolate that.

2022-09-17 19:45 UTC, stevapple commented
@compnerd I’m willing to further investigate the problem in a new issue in apple/swift. So for this PR could you test on your machine? I believe this is a pure NFC and thus should introduce no public behavioral change.

2022-09-18 17:55 UTC, compnerd requested changes
This seems to cause a pretty bad regression on Windows.  At the very least these tests now crash:

```
Test Suite 'Selected tests' started at 2022-09-18 10:50:07.201
Test Suite 'AntisymmetryTest' started at 2022-09-18 10:50:07.206
Test Case 'AntisymmetryTest.testAntisymmetricTopLevelDefs' started at 2022-09-18 10:50:07.206
Test Suite 'Selected tests' started at 2022-09-18 10:50:07.185
Test Suite 'AddFuncInImportedExtensionTest' started at 2022-09-18 10:50:07.185
Test Case 'AddFuncInImportedExtensionTest.testAddFuncInImportedExtension' started at 2022-09-18 10:50:07.185
Test Suite 'Selected tests' started at 2022-09-18 10:50:15.301
Test Suite 'APIDigesterTests' started at 2022-09-18 10:50:15.306
Test Case 'APIDigesterTests.testABIDigesterRequirements' started at 2022-09-18 10:50:15.306
Test Suite 'Selected tests' started at 2022-09-18 10:50:15.276
Test Suite 'SpecificFuncAdditionInExtensionWithinModuleTest' started at 2022-09-18 10:50:15.281
Test Case 'SpecificFuncAdditionInExtensionWithinModuleTest.testSpecificFuncAdditionInExtensionWithinModule' started at 2022-09-18 10:50:15.281
Test Suite 'Selected tests' started at 2022-09-18 10:50:15.307
Test Suite 'HideAndShowFuncInStructAndExtensionTests' started at 2022-09-18 10:50:15.313
Test Case 'HideAndShowFuncInStructAndExtensionTests.testHideAndShowFuncInStructAndExtension' started at 2022-09-18 10:50:15.313
Test Suite 'Selected tests' started at 2022-09-18 10:50:15.293
Test Suite 'RenameMemberOfImportedStructTest' started at 2022-09-18 10:50:15.298Test Case 'RenameMemberOfImportedStructTest.testRenamingMember' started at 2022-09-18 10:50:15.298
Test Suite 'Selected tests' started at 2022-09-18 10:50:15.307
Test Suite 'AntisymmetryTest' started at 2022-09-18 10:50:15.313
Test Case 'AntisymmetryTest.testAntisymmetricTopLevelUses' started at 2022-09-18 10:50:15.313
Test Suite 'Selected tests' started at 2022-09-18 10:50:15.304
Test Suite 'TransitivityTest' started at 2022-09-18 10:50:15.309
Test Case 'TransitivityTest.testTransitiveTopLevelUses' started at 2022-09-18 10:50:15.309
Test Suite 'Selected tests' started at 2022-09-18 10:50:15.308
Test Suite 'TransitivityTest' started at 2022-09-18 10:50:15.314
Test Case 'TransitivityTest.testTransitiveStructMember' started at 2022-09-18 10:50:15.314
Test Suite 'Selected tests' started at 2022-09-18 10:50:29.404Test Suite 'APIDigesterTests' started at 2022-09-18 10:50:29.404Test Case 'APIDigesterTests.testBaselineGenerationJobFlags' started at 2022-09-18 10:50:29.404warning: no such SDK: /path/to/sdk
Test Suite 'Selected tests' started at 2022-09-18 10:50:29.389
Test Suite 'APIDigesterTests' started at 2022-09-18 10:50:29.393
Test Case 'APIDigesterTests.testBaselineOutputPath' started at 2022-09-18 10:50:29.394
Test Suite 'Selected tests' started at 2022-09-18 10:50:29.387
Test Suite 'APIDigesterTests' started at 2022-09-18 10:50:29.392
Test Case 'APIDigesterTests.testBaselineGenerationRequiresTopLevelModule' started at 2022-09-18 10:50:29.392
Test Suite 'Selected tests' started at 2022-09-18 10:50:29.400
Test Suite 'APIDigesterTests' started at 2022-09-18 10:50:29.404
Test Case 'APIDigesterTests.testDigesterModeValidation' started at 2022-09-18 10:50:29.404
Test Suite 'Selected tests' started at 2022-09-18 10:50:29.343
Test Suite 'APIDigesterTests' started at 2022-09-18 10:50:29.348
Test Case 'APIDigesterTests.testComparisonOptionValidation' started at 2022-09-18 10:50:29.348
Test Suite 'Selected tests' started at 2022-09-18 10:50:37.749
Test Suite 'CrossModuleIncrementalBuildTests' started at 2022-09-18 10:50:37.749Test Case 'CrossModuleIncrementalBuildTests.testChangingOutputFileMap' started at 2022-09-18 10:50:37.749
Test Suite 'Selected tests' started at 2022-09-18 10:50:37.749
Test Suite 'CrossModuleIncrementalBuildTests' started at 2022-09-18 10:50:37.749
Test Case 'CrossModuleIncrementalBuildTests.testEmbeddedModuleDependencies' started at 2022-09-18 10:50:37.749
Test Suite 'Selected tests' started at 2022-09-18 10:50:37.749
Test Suite 'AssertDiagnosticsTests' started at 2022-09-18 10:50:37.749
Test Case 'AssertDiagnosticsTests.testAssertDriverDiagosotics' started at 2022-09-18 10:50:37.749
Test Suite 'Selected tests' started at 2022-09-18 10:50:37.749
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:37.749Test Case 'ExplicitModuleBuildTests.testDependencyGraphDotSerialization' started at 2022-09-18 10:50:37.749
Test Suite 'Selected tests' started at 2022-09-18 10:50:45.827
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:45.830Test Case 'ExplicitModuleBuildTests.testModuleAliasingInterfaceWithScanDeps' started at 2022-09-18 10:50:45.830
Test Suite 'Selected tests' started at 2022-09-18 10:50:45.659
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:45.664
Test Case 'ExplicitModuleBuildTests.testDependencyScanReuseCache' started at 2022-09-18 10:50:45.664
Test Suite 'Selected tests' started at 2022-09-18 10:50:45.699
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:45.704Test Case 'ExplicitModuleBuildTests.testDependencyScanning' started at 2022-09-18 10:50:45.704
Test Suite 'Selected tests' started at 2022-09-18 10:50:45.650
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:45.655
Test Case 'ExplicitModuleBuildTests.testDependencyScanningNoResponse' started at 2022-09-18 10:50:45.655
Test Suite 'Selected tests' started at 2022-09-18 10:50:45.648
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:45.655
Test Case 'ExplicitModuleBuildTests.testDependencyScanningFailure' started at 2022-09-18 10:50:45.655
Test Suite 'Selected tests' started at 2022-09-18 10:50:45.668
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:45.671
Test Case 'ExplicitModuleBuildTests.testDependencyImportPrescan' started at 2022-09-18 10:50:45.671
Test Suite 'Selected tests' started at 2022-09-18 10:50:50.264
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:50.270
Test Case 'ExplicitModuleBuildTests.testModuleAliasingPrebuiltWithScanDeps' started at 2022-09-18 10:50:50.270
Test Suite 'Selected tests' started at 2022-09-18 10:50:57.130
Test Suite 'IncrementalCompilationTests' started at 2022-09-18 10:50:57.134Test Case 'IncrementalCompilationTests.testAddingInput' started at 2022-09-18 10:50:57.135*** starting build initial ***
Test Suite 'Selected tests' started at 2022-09-18 10:50:54.996
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:55.004
Test Case 'ExplicitModuleBuildTests.testModuleAliasingWithExplicitBuild' started at 2022-09-18 10:50:55.005
Test Suite 'Selected tests' started at 2022-09-18 10:50:55.042
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:55.047
Test Case 'ExplicitModuleBuildTests.testModuleAliasingWithImportPrescan' started at 2022-09-18 10:50:55.047
Test Suite 'Selected tests' started at 2022-09-18 10:50:55.056
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:55.061
Test Case 'ExplicitModuleBuildTests.testModuleDependencyBuildCommandGenerationWithExternalFramework' started at 2022-09-18 10:50:55.061
Test Suite 'Selected tests' started at 2022-09-18 10:50:55.089
Test Suite 'ExplicitModuleBuildTests' started at 2022-09-18 10:50:55.094Test Case 'ExplicitModuleBuildTests.testPrintingExplicitDependencyGraph' started at 2022-09-18 10:50:55.094
Test Suite 'Selected tests' started at 2022-09-18 10:51:01.216
Test Suite 'IncrementalCompilationTests' started at 2022-09-18 10:51:01.216Test Case 'IncrementalCompilationTests.testAlwaysRebuildDependents' started at 2022-09-18 10:51:01.216*** starting build initial ***
Test Suite 'Selected tests' started at 2022-09-18 10:51:03.593
Test Suite 'IncrementalCompilationTests' started at 2022-09-18 10:51:03.613
Test Case 'IncrementalCompilationTests.testBuildRecordDateAccuracy' started at 2022-09-18 10:51:03.614*** starting build initial ***
Test Suite 'Selected tests' started at 2022-09-18 10:51:03.619
Test Suite 'IncrementalCompilationTests' started [...]

2022-09-18 19:23 UTC, stevapple commented
Fixed a silly bug — now the test suite can run and all failures are irrelevant (around several parsing tests).

![CE489490-FF7D-4A96-B3A9-F556E8A63A3A](https://user-images.githubusercontent.com/26525394/190924806-cfc6886b-cd5d-4847-9892-34971e75836a.jpeg)
![F3FC1439-8C31-4C07-8DDF-18A3E01E523B](https://user-images.githubusercontent.com/26525394/190924820-c019b382-9a06-4bde-8ba7-99dc37a2c6ba.jpeg)

2022-09-19 15:00 UTC, compnerd approved these changes
Running locally found 2 tests fail (6 failures) but they don't seem related to this change.

2022-09-19 15:04 UTC, compnerd commented
@swift-ci please test

2022-09-19 17:16 UTC, compnerd commented
@swift-ci please test Windows platform

2022-09-20 14:47 UTC, merged