Package.swift: bump ArgumentParser to 1.1.4
apple/swift-driver pull request #1218
Opened 2022-11-07 17:48 UTC by MaxDesiatov

2022-11-07 17:52 UTC, artemcm commented
@MaxDesiatov this repository does not support cross-repo CI. 
Instead, it should be launched from `apple/swift` with the mention of this PR.

2022-11-07 17:53 UTC, MaxDesiatov commented
Fair enough, thanks for the guidance 👍

2022-11-07 21:30 UTC, MaxDesiatov commented
@swift-ci please test

2022-11-12 15:33 UTC, MaxDesiatov commented
@swift-ci please test

2022-12-07 11:32 UTC, MaxDesiatov commented
@swift-ci please test

2022-12-07 13:27 UTC, MaxDesiatov commented
@swift-ci please test Windows

2022-12-07 17:33 UTC, MaxDesiatov commented
@swift-ci please test Windows

2022-12-13 21:36 UTC, MaxDesiatov commented on Utilities/build-script-helper.py
> -  for lib in ['libArgumentParser', 'libArgumentParserToolInfo']:
@DougGregor this is a change I have doubts about, but it apparently makes the error in this CI run go away: https://ci.swift.org/job/swift-PR-macos/5203/console

2022-12-13 21:36 UTC, MaxDesiatov commented
@swift-ci please test

2022-12-14 19:17 UTC, MaxDesiatov commented
@swift-ci please test

2022-12-14 19:21 UTC, MaxDesiatov commented
@swift-ci please test

2022-12-14 19:21 UTC, artemcm approved these changes
Looks good. Thanks for the extension fixes to `build-script-helper.py`

2023-01-03 17:29 UTC, MaxDesiatov commented
@swift-ci please test

2023-01-04 03:15 UTC, rauhul commented
Just wondering, any reason to not pull in 1.2.0?

2023-01-04 07:33 UTC, MaxDesiatov commented
There's a regression in 1.2.0 due to which SwiftPM bootstrap build fails.

2023-01-04 11:26 UTC, MaxDesiatov commented
@swift-ci test Windows

2023-01-04 13:00 UTC, compnerd commented
Bleh, the windows failure looks like a regression in LSP (wonder if the windows build got triggered on changes 🤔)

2023-01-04 13:02 UTC, compnerd requested changes
Windows does a shared link to s-a-p.  We should bump this in swift in update-checkout-config.json and in the other packages (SPM, LSP).

2023-01-04 13:10 UTC, MaxDesiatov commented
It has been bumped in all other places, I have corresponding PRs waiting to be merged. Do your expect any additional changes to this PR specifically?

2023-01-04 14:05 UTC, compnerd commented
Please test with following PRs:
apple/sourcekit-lsp#689

@swift-ci please test Windows platform

2023-01-04 14:09 UTC, MaxDesiatov commented
I've been told upthread that this repository doesn't support cross-repo testing, but I hope that Windows CI run passes anyway

2023-01-05 11:03 UTC, MaxDesiatov commented
@swift-ci test Windows

2023-01-05 14:43 UTC, MaxDesiatov commented
@compnerd Windows build is passing now, would you mind re-reviewing? Thanks!

2023-01-05 15:29 UTC, compnerd approved these changes
The change itself looks fine, but please make sure that you do a cross-repo test in apple/swift with `@swift-ci please build toolchain Windows platform` and then test the resulting installer.  The problem is that there can be something subtle in the packaging where a dependency is either missing and expected or is missing and unexpected and the tools will not function.

2023-01-05 15:38 UTC, MaxDesiatov commented
@compnerd thank you. I've pinged you in the corresponding PR, for some reason the Windows toolchain CI run can't find artifacts, even though there are no obvious failures. I've shared the error message here https://github.com/apple/swift/pull/59009#issuecomment-1371308975

2023-01-05 15:40 UTC, compnerd commented
@MaxDesiatov - that is what happens when the necessary changes are missing!  You need a parallel change to apple/swift-installer-scripts: https://github.com/apple/swift/pull/59009#pullrequestreview-1235971354

2023-01-05 17:40 UTC, MaxDesiatov commented
That did indeed help, thanks for the review and finding the root cause of the build failure!

2023-01-10 08:40 UTC, merged