Only add '-fobjc-link-runtime' to the linker invocation when the drivr is invoked with '-link-objc-runtime'
apple/swift-driver pull request #1224
Opened 2022-11-15 17:10 UTC by artemcm

Otherwise, every single compiled program will end up linking it, and Foundation on top of it.

2022-11-15 17:12 UTC, DougGregor approved these changes

2022-11-15 17:13 UTC, artemcm commented
@swift-ci test

2022-11-15 17:13 UTC, compnerd commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> +    if parsedOptions.hasFlag(positive: .linkObjcRuntime,
Is this an existing option?  Why not gate this on `-enable-objc-interop`?

2022-11-15 17:16 UTC, artemcm commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> +    if parsedOptions.hasFlag(positive: .linkObjcRuntime,
It is an existing option and seems to very explicitly map to Clang's equivalent. 

I am not sure if there are cases where `-enable-objc-interop` is set where we wouldn't want to do this though, explicit override with `-no-link-obcj-runtime` aside...

2022-11-15 17:18 UTC, compnerd commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> +    if parsedOptions.hasFlag(positive: .linkObjcRuntime,
The only question then is, is there ever a case where you want to link the ObjC runtime (and Foundation) when ObjC is explicitly disabled?  If not, I feel like `-enable-objc-interop` is nicer.

2022-11-15 17:23 UTC, artemcm commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> +    if parsedOptions.hasFlag(positive: .linkObjcRuntime,
`-enable-objc-interop` is actually a frontend-only flag (`.noDriver`) that the driver sets to be on by-default for Darwin platforms, always. 

So we cannot use it as an input switch to enable/disable this. And if we did, because it is enabled by the driver by-default, it would essentially be equivalent to what things were like before this change. I may lack some historical context here, but the existence of `-link-objc-runtime` really indicates that it ought to be used to control this behavior.

2022-11-15 17:25 UTC, compnerd commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> +    if parsedOptions.hasFlag(positive: .linkObjcRuntime,
Yeah, as a short term thing, I don't think that it is terrible.  But it seems like having an extra flag that is unnecessary and we should figure out how to deprecate that IMO.  Having the language runtime be linked in properly based on the build type seems like the right approach.

2022-11-15 17:26 UTC, compnerd requested changes

2022-11-15 17:26 UTC, compnerd commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
>        "-lobjc",
Should `-lobjc` be dropped now?  This should be handled by `-fobjc-link-runtime` in the clang driver.

2022-11-15 17:27 UTC, artemcm commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
>        "-lobjc",
Yup. https://github.com/apple/llvm-project/blob/cached/stable/20220421/clang/lib/Driver/ToolChains/Darwin.cpp#L751

2022-11-15 17:29 UTC, artemcm commented
@swift-ci test

2022-11-15 17:36 UTC, artemcm commented
@swift-ci test

2022-11-15 17:37 UTC, artemcm commented
@swift-ci test

2022-11-15 17:43 UTC, merged

2022-11-15 18:38 UTC, Catfish-Man commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> +    if parsedOptions.hasFlag(positive: .linkObjcRuntime,
It's not that there are cases where you want this without ObjC, but there are cases where you want ObjC without this. For example, if you're in a binary which Foundation itself links.

2022-11-15 18:38 UTC, Catfish-Man commented on Sources/SwiftDriver/Jobs/DarwinToolchain+LinkerSupport.swift
> +    if parsedOptions.hasFlag(positive: .linkObjcRuntime,
(and then you manually link the runtime of course. I'm not aware of a situation where you want ObjC support but not the ObjC runtime, it's just Foundation that makes things tricky)

2022-11-16 00:39 UTC, DougGregor commented
This might be causing CI failures in LLDB. Speculatively reverting to do more testing