Add support for automatically emit API descriptor files
apple/swift-driver pull request #1478
Opened 2023-11-01 19:42 UTC by zixu-w

2023-11-01 20:02 UTC, artemcm approved these changes

2023-11-01 20:47 UTC, zixu-w commented
@swift-ci please test

2023-11-01 20:54 UTC, tshortli requested changes
There are a couple uses of new Swift syntax in this PR that use new language features only available in the Swift 5.9 compiler. For now I think we expect to maintain compatibility with Swift 5.8 and so the syntax should be tweaked.

2023-11-01 20:54 UTC, tshortli commented on Sources/SwiftDriver/Driver/Driver.swift
> +    let apiDescriptorDirectory: VirtualPath? = if let apiDescriptorDirectoryEnvVar = env["TAPI_SDKDB_OUTPUT_PATH"] {
This should be refactored to avoid using `if` expressions to avoid a dependency on the Swift 5.9 compiler for now.

2023-11-01 20:54 UTC, tshortli commented on Sources/SwiftDriver/Driver/Driver.swift
> +    if let apiDescriptorDirectory {
```suggestion
    if let apiDescriptorDirectory = apiDescriptorDirectory {
```
Again, to avoid a dependency on Swift 5.9 language features.

2023-11-01 21:07 UTC, zixu-w commented on Sources/SwiftDriver/Driver/Driver.swift
> +    let apiDescriptorDirectory: VirtualPath? = if let apiDescriptorDirectoryEnvVar = env["TAPI_SDKDB_OUTPUT_PATH"] {
Ah I didn't realize I was using the new syntax. Will look into refactoring

2023-11-01 22:26 UTC, tshortli approved these changes

2023-11-01 22:38 UTC, zixu-w commented
@swift-ci please test

2023-11-02 00:11 UTC, zixu-w commented
@swift-ci please test Windows

2023-11-03 17:26 UTC, merged