Update Generic Unix linker selection
apple/swift-driver pull request #1545
Opened 2024-02-16 03:58 UTC by etcwilde

Not all generic-"unix" environments have the Gold linker available to them, and in some cases, the vendor of the toolchain may provide their own linker. In these cases, the driver should be internally consistent with the toolchain that it is shipped with.

Now that we have the clang-linker, we can lean on the linker selection in the clang-linker to determine a default linker. If the clang-linker, and thus, the swift compiler driver, are part of a specific toolchain, that clang-linker should be built for that platform with the appropriate linker defaults set. If someone overrides the linker with `-use-ld`, we should still honour that, but should otherwise be consistent with the appropriate toolchain linker.

This will enable building and linking on AmazonLinux 2023 without requiring folks to always pass additional flags. It also means we can produce a self-contained toolchain that is internally consistent using `lld` as the linker.

I've posted https://github.com/apple/llvm-project/pull/8214 to workaround the symbol munging introduced into `lld` in https://reviews.llvm.org/D96914. 

Fixes: rdar://123061492

2024-02-16 03:59 UTC, etcwilde commented
https://github.com/apple/llvm-project/pull/8214
@swift-ci please test

2024-02-16 04:05 UTC, etcwilde commented
https://github.com/apple/llvm-project/pull/8214
@swift-ci please test

2024-02-16 15:16 UTC, compnerd commented
@swift-ci please test Windows platform

2024-02-16 16:42 UTC, keith approved these changes

2024-02-20 16:51 UTC, artemcm approved these changes

2024-03-03 09:16 UTC, finagolfin requested changes
LGTM, but test nits.

2024-03-03 09:16 UTC, finagolfin commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> -        .flag("-Xlinker"), .flag("-z"), .flag("-Xlinker"), .flag("nostart-stop-gc")]))
Change this to `XCTAssertTrue(lastJob.commandLine.contains(.flag("-fuse-ld=lld")))` instead, so we have a test of overriding the linker with a Unix toolchain.

2024-03-03 09:16 UTC, finagolfin commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> -      XCTAssertTrue(lastJob.commandLine.contains(.flag("-fuse-ld=lld")))
This test block can be removed altogether, as you're removing the FreeBSD logic it was added to test in #1211.

2024-03-04 05:55 UTC, etcwilde commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> -        .flag("-Xlinker"), .flag("-z"), .flag("-Xlinker"), .flag("nostart-stop-gc")]))
Fixed

2024-03-04 05:55 UTC, etcwilde commented on Tests/SwiftDriverTests/SwiftDriverTests.swift
> -      XCTAssertTrue(lastJob.commandLine.contains(.flag("-fuse-ld=lld")))
Fixed

2024-03-04 06:02 UTC, etcwilde commented
@swift-ci please test

2024-03-04 06:35 UTC, finagolfin approved these changes
Thanks, this is a good change that we probably should've been doing all along.

2024-03-04 08:11 UTC, MaxDesiatov commented
@swift-ci test windows

2024-05-04 18:42 UTC, etcwilde commented
@swift-ci please test

2024-05-04 21:27 UTC, shahmishal approved these changes

2024-05-06 18:12 UTC, merged

2024-09-28 17:17 UTC, sebsto commented
@MaxDesiatov @etcwilde This has been merged in `main` but was not cherry picked for `release/6.0.0` nor `release/6.0.2`
Toolchains built on Amazon Linux 2023 without this can only be used on machines where `ld.gold` is installed.

Can we include this change in one of the next release ?