Implement WindowsToolchain
apple/swift-driver pull request #252
Opened 2020-09-13 16:11 UTC by stevapple

Implemented the Windows-specific toolchain.

2020-09-13 16:12 UTC, stevapple commented
CC @compnerd , I hope to get SPM fully usable on Windows through `swift-driver`.

2020-09-13 17:31 UTC, compnerd requested changes

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
> +          case .aarch64, .aarch64_32: return "arm64"
`.aarch64_32` makes no sense on Windows.  There is no 32-bit ABI for ARM64 on Windows that is distinct from ARMv7.  That should be a `fatalError`.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
> +      let vctools = env["VCToolsInstallDir"],
I would rather not dig for clang resources from the `VCToolsInstallDir`.  You should use the path relative location for clang resources.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
> +// TODO: See whether Windows needs `addArgsToLinkStdlib`.
Yes, it will definitely needs arguments for that.  At the very least, you need to ensure that the ucrt link matches the stdlib.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +        commandLine.appendFlag("-emit-executable")
Can you duplicate rather than try to share the logic here?  You are always adding `-emit-executable` even in the shared case.

Nit: indentation is off.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +          }
This stanza doesn't make sense.  Windows does not support `-rpath`.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +        } else {
I don't think that we want to use these.  The response file support in GNU is different from MSVC.  Additionally, Windows is significantly friendlier - we can use linker directives to achieve this in a much more reasonable fashion.  I think that this should be something like `if !no_stdlib { commandLine.appendFlag("-lswiftCore") }`.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +        }
This can be entirely dropped.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +        commandLine.appendFlag("--target=\(targetTriple.triple)")
Please use the split form.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +                                   "libclangrt_profile-\(targetTriple.archName).a")
Please derive the prefix and suffix from the platform settings.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +          commandLine.appendFlag("-u__llvm_profile_runtime")
There is no `-u` flag that is part of the LINK specification.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +
I don't see `-use-ld` being forwarded here?

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +    } else if !["swift-frontend", "swift", "swift-frontend.exe", "swift.exe"].contains(executable),
Can you derive the names from the platform instead?

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +    case .staticLibrary: return "\(moduleName).lib"
You should add a case for an import library

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "lld-link.exe")
I think that we should derive this based on `-use-ld`.  The default should be `link.exe`, unless otherwise specified.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "dsymutil.exe")
There is no `dsymutil` support on Windows.  The PDB is generated by `link`.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "swift-autolink-extract.exe")
`swift-autolink-extract` should never be used when targeting Windows.  When will this hit?

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "llvm-lib.exe")
This should be controlled by `-use-ld`.  The default should be `link`, `lld` if `-use-ld=lld` is specified.

2020-09-13 17:31 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
What is this used for?  I would imagine that the `runtimeLibraryName` should be the import library, not the DLL.

2020-09-13 23:06 UTC, stevapple commented on Sources/SwiftDriver/Jobs/Toolchain+LinkerSupport.swift
> +      let vctools = env["VCToolsInstallDir"],
You mean search for clang resources in the whole `%PATH%`?

2020-09-13 23:07 UTC, stevapple commented on Sources/SwiftDriver/Jobs/WindowsToolchain+LinkerSupport.swift
> +        commandLine.appendFlag("-emit-executable")
Sorry, this is a bug😢Will fix in the next commit

2020-09-13 23:09 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "dsymutil.exe")
So how should we handle here? Directly return `nil` or return something else?

I’ve found `dsymutils.exe` in the packaged toolchain, so...

2020-09-13 23:10 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "swift-autolink-extract.exe")
Probably not, but it exists so I put it here. Return `nil` instead? I think it’s okay to keep it.

2020-09-13 23:24 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
On Linux it returns things like `clang_rt.asan-x86_64.a`. It’s a typo here (I intended to use `.lib` but...), and sorrily I didn’t find any `exp`s.

2020-09-13 23:28 UTC, owenv commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "dsymutil.exe")
Trying to lookup dsymutil can probably just call fatalError(), I'm not sure why we're not already doing that on Linux

2020-09-13 23:28 UTC, owenv commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      return try lookup(executable: "swift-autolink-extract.exe")
Same here, this can be a fatalError because trying to look it up with a Windows toolchain is a programming error in the driver.

2020-09-13 23:29 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
Do you have a Windows on ARM device to see what the `arch` part in `clang_rt` is for `arm` and `aarch64`? I assumed them to `arm` and `arm64`, but not for sure. Or is there any way to install ARM runtime support on `x64` devices?

2020-09-13 23:32 UTC, owenv commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
This is used indirectly by `parseSanitizerArgValues` to determine whether sanitizers are supported based on whether the libraries can be found on disk. It's not necessarily something we want to keep long term though, there's a FIXME:
```
// FIXME: Should we do this? This prevents cross-compiling with sanitizers
//        enabled.
```

2020-09-14 00:10 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
They should be `armv7` and `aarch64`.  The only one to use `arm64` is Apple.

2020-09-14 02:09 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
Windows has a very weird directory structure...For `x86_64`, it’s parent name is `x64`; for `i386`, it is `x86`. There’s even no `x86` here in `clang_rt`. we probably need a real Surface Pro X to make it sure.

2020-09-14 02:40 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
I think that the Windows directory structure actually makes far more sense.  i386 doesn't make sense, it isn't i386, the modern derivates of it became 486, 586, 686, Pentium, and then Core.  These are all x86 derivates, but far different from i386.  x64 makes sense, it is a contraction of x86_64.  Correct, the ASAN libraries are not from MSVC or Microsoft, they are from the work that Google did, which is why its not surprising at all that the library does not exist there.  I don't think that the Surface Pro X is going to help as there is no VS on the device AFAIK.

2020-09-14 05:46 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +  public func runtimeLibraryName(
Fixed this part

2020-09-14 13:01 UTC, stevapple commented
I’m working on the linker part, and I’m now troubled by the following two question:

- Can we use things like `link.exe` and `lib.exe` in Cygwin and MingW? That is, is `link.exe` and `lib.exe` available to everyone using Swift for Windows?
- Do we also have `llvm-lib.exe` and `lldb-link.exe` in Cygwin and MingW toolchains?

It’s fairly easy to configure the MSVC linkers and their LLVM drop-in substitutes (I think it can be done today), but what about not using `msvc` here?

Also, we’re not using `cl.exe` here, right?

2020-09-14 15:27 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +    case .staticLibrary: return "\(moduleName).lib"
Sadly, we cannot generate an import library for the moment. The binary of Swift code doesn’t contain the flags necessary for it, and we also have no `.def` file. `link.exe` needs at least [one of four marks](https://docs.microsoft.com/zh-cn/cpp/build/reference/export-exports-a-function?view=vs-2019) to generate an import library.

2020-09-14 15:28 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +    case .staticLibrary: return "\(moduleName).lib"
If we can fill out one of those, please point out for me🙏thx a lot

2020-09-14 16:07 UTC, stevapple commented
Another question that I think only @compnerd is capable of answering... Are we going to include `clangLibrary` with Swift? If the answer is “yes”, then things will be much easier because we don’t need to search for clang libraries.

2020-09-14 16:40 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +    case .staticLibrary: return "\(moduleName).lib"
P.S. `link.exe` can automatically infer import library name from output file name (by default, it *will* generate an import library as long as the requirements are satisfied), so I think there’s no need to add a specific `OutputLinkType` for it.

2020-09-15 14:27 UTC, compnerd commented
The MinGW path should not use the WindowsToolchain but rather the GNUToolchain much Like the model in clang.  MinGW is substantially different in ABI that you cannot mix and match the behavior.  In fact there's a large number of other things that won't work - like linking because MinGW would require auto link extract that the Windows path does not use as the MINGW doesn't support linker directives.  The other thing is that binutils isn't supported by swift because of issues with relocation handling.  In general, MinGW isn't ready yet, and would require a lot more than just tweaking the driver.

No, there's no reason to include clangrt, that isn't used on windows.

2020-09-15 14:32 UTC, stevapple commented
clang_rt is required for sanitizer support.

```swift
    // Check that we're one of the known supported targets for sanitizers.
    if !(targetTriple.isWindows || targetTriple.isDarwin || targetTriple.os == .linux)
```

I’m seeing this line of code. It should mean that we are going to provide sanitizer support on Windows?

2020-09-16 16:31 UTC, stevapple commented
Finally gets a solution for sanitizer support. I’m going to filter out any sanitizer other than ASAN. This means if anyone builds his copy with `clang_rt`, he’ll be able to use ASAN. Other sanitizers will be blocked even if their libraries exist.

2020-09-17 05:05 UTC, owenv reviewed
Thanks for updating this! It looks pretty good to me, but I'm not very familiar with Windows so I wasn't able to review it thoroughly.

It would be really great if we could include some basic tests alongside this change as well, at least for the platform-specific linking. I think a lot of the windows-related integration tests from the main Swift repo will continue to fail until MSVC runtime handling is added, I haven't looked into how complicated that is. Maybe a couple cases could be added to `testLinking` in `SwiftDriverTests.swift` that use the windows target?

2020-09-17 05:23 UTC, stevapple commented on Sources/SwiftDriver/Driver/Driver.swift
> +    if targetTriple.isWindows {
👌I’ll take the advice

2020-09-17 06:33 UTC, stevapple commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +  var executableSuffix: String { get }
I think so. Fixed👌

2020-09-17 07:36 UTC, stevapple commented
> It would be really great if we could include some basic tests alongside this change as well, at least for the platform-specific linking. I think a lot of the windows-related integration tests from the main Swift repo will continue to fail until MSVC runtime handling is added, I haven't looked into how complicated that is. Maybe a couple cases could be added to testLinking in SwiftDriverTests.swift that use the windows target?

Of course I will. However, there is still an unimplemented function (see the only unresolved review😂) which should be implemented before implementing tests.

2020-09-17 16:00 UTC, stevapple commented
Shall we use MD or MT as default for Windows? @compnerd

2020-09-17 18:30 UTC, compnerd commented
I don't think that we should have a default for the value.  It _must_ match the value for the runtime that you are building against.  I suppose that one possibility is to query the `SDKSettings.plist` for the correct value like I have done in swift-package-manager.  But, really, I think that we should have the user specify the correct value.

2020-09-18 01:08 UTC, stevapple commented
I think it necessary. It’s one of our goals to allow user run `swiftc` without any additional options, which means we should be able to infer every parameter we need from the context. We can have multiple ways to infer though, plist is one of them, but maybe we also need a hard-coded default.

2020-09-18 02:58 UTC, compnerd commented
If you are adamant that you must have a default, then you must serialize the compile options into the `Swift.swiftmodule` and then deserialize it to find the default at runtime.  Otherwise, whatever default you choose is the wrong one - my runtime will always be the inverse of whatever the default is, and therefore you have just built a binary that will arbitrarily crash.

2020-09-18 03:12 UTC, stevapple commented
I‘d like to know if `SDKSettings.plist` is built alongside with Windows SDK. If it is (which means every copy of Windows SDK contains `SDKSettings.plist`), we won’t need an extra default. That would be great and simple.

2020-09-18 04:16 UTC, compnerd commented
It is not, it is only something that is built on my builds of the toolchain; anyone building the toolchain manually will have to deal with that themselves.

2020-10-05 23:58 UTC, closed without merging

2020-10-06 20:27 UTC, shahmishal commented
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create the pull request with `main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412