[Incremental] Centralize fingerprint/swiftmodule invariant, catch bad paths earlier
apple/swift-driver pull request #486
Opened 2021-02-11 23:58 UTC by davidungar

Centralizes the enforcement of the aforementioned invariant. Also makes the fields of a `SourceModuleDependencyGraph.Node` immutable. Catches bad external dependency paths as soon as possible.

2021-02-11 23:58 UTC, davidungar commented
@swift-ci please test

2021-02-12 00:00 UTC, davidungar commented
@swift-ci please test

2021-02-12 00:00 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/KeyAndFingerprintHolder.swift
> +//===------- KeyAndFingerprintEnforcer.swift ------------------------------===//
```suggestion
//===------- KeyAndFingerprintHolder.swift -------------------------------===//
```

2021-02-12 00:51 UTC, CodaFi commented on Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
> +    allNodes[newUse.sequenceNumber] = newUse
This is... rather expensive.

2021-02-12 00:52 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/DependencyKey.swift
> +  /*@_spi(Testing)*/ public init(_ fileName: String)
Thanks!

2021-02-12 00:55 UTC, CodaFi requested changes
I appreciate trying to push immutability in more places, but this PR will have the unfortunate effect of making node construction incur roughly factorial copies in the number of def-use arcs added during graph construction. Perhaps we could explore a lowering step where the node data is collected and all the arcs are gathered, then we "commit" and lower that data to the actual graph nodes.

2021-02-12 00:59 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/KeyAndFingerprintHolder.swift
> +//===------- KeyAndFingerprintEnforcer.swift ------------------------------===//
D'Oh! Thanks.

2021-02-12 01:02 UTC, davidungar commented on Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
> +    allNodes[newUse.sequenceNumber] = newUse
Yes, I'll think about a better way.

2021-02-12 01:04 UTC, davidungar commented
> I appreciate trying to push immutability in more places, but this PR will have the unfortunate effect of making node construction incur roughly factorial copies in the number of def-use arcs added during graph construction. Perhaps we could explore a lowering step where the node data is collected and all the arcs are gathered, then we "commit" and lower that data to the actual graph nodes.

That's a fair point. I see where happens in the test. I think that's the only place (in the driver). I'll look at doing as you suggest.

2021-02-12 01:25 UTC, CodaFi commented
(Correction *the number of copies is roughly a triangular sum, not a product. That makes it quadratic)

2021-02-12 01:48 UTC, davidungar commented
@swift-ci please test

2021-02-12 03:50 UTC, davidungar commented
> (Correction *the number of copies is roughly a triangular sum, not a product. That makes it quadratic)

Yes, that sounds more accurate.

2021-02-12 03:53 UTC, davidungar commented
@swift-ci  please test

2021-02-12 04:19 UTC, davidungar commented
@CodaFi How does it look now?

2021-02-12 04:19 UTC, davidungar commented
@swift-ci please test

2021-02-12 04:28 UTC, davidungar commented
rebased onto master

2021-02-12 04:28 UTC, davidungar commented
@swift-ci please test

2021-02-12 06:36 UTC, cltnschlosser commented on Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
> +    while dependencyAccumulator.count <= use.sequenceNumber {
I don't know the context of these numbers, so maybe it doesn't make sense, but should you reserveCapacity in the array before the loop?

2021-02-12 06:36 UTC, cltnschlosser commented on Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
> +    }()
I wrote this thinking this was a dictionary at first, but it's not, so this doesn't really apply. But maybe could make something like this. I think it increases readability, but completely up to you. Might be weird for an array to have that subscript.
```suggestion
    var dh = dependencyAccumulator[use.sequenceNumber, default: DependencyHolder()]
```

Related, any reason or advantage to having this be an array of optionals? Or would in make sense to append DependencyHolders in the loop instead of nil

2021-02-12 17:39 UTC, davidungar commented on Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
> +    }()
It is an optimization, since a number have no entries. But its a good question.

2021-02-12 17:40 UTC, davidungar commented on Tests/SwiftDriverTests/ModuleDependencyGraphTests.swift
> +    while dependencyAccumulator.count <= use.sequenceNumber {
Yes, I should. Great point. Thanks for reviewing.

2021-02-12 17:43 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +      let extModTime = (try? fileSystem.getFileInfo(extDep.file).modTime)
Thanks; nice catch!

2021-02-12 17:45 UTC, davidungar commented
@swift-ci please test

2021-02-12 18:31 UTC, CodaFi approved these changes

2021-02-12 18:31 UTC, CodaFi commented
⛵

2021-02-12 18:31 UTC, merged

2021-02-12 18:32 UTC, davidungar commented
> ⛵

Thank you!