[Incremental Imports] Add framework and new tests
apple/swift-driver pull request #521
Opened 2021-03-03 00:38 UTC by davidungar

Adds a new test framework, and uses it for two multi-module, incremental import tests.

2021-03-03 00:39 UTC, davidungar commented
@swift-ci please test

2021-03-03 00:57 UTC, CodaFi commented on Tests/SwiftDriverTests/Helpers/IncrementalImportTestFramework.swift
> + protocol IITF_TestProtocol {
Swift code generally doesn't use prefixes. You can make a separate test-only module if you are worried about encapsulation.

2021-03-03 00:58 UTC, CodaFi commented on Tests/SwiftDriverTests/IncrementalImportTests.swift
> +    case ImportedModule, MainModule
Swift 3+ uses lower camel case enum identifiers.

2021-03-03 00:59 UTC, CodaFi commented on Tests/SwiftDriverTests/IncrementalImportTests.swift
> +    case ImportedModule, MainModule
Casing

2021-03-03 01:00 UTC, CodaFi commented on Tests/SwiftDriverTests/IncrementalImportTests.swift
> +          .init("""
This DSL spelling feels like the pendulum has swung really really far in favor of terseness. I would prefer to see a more instantly-readable set of declarations here. For example, type names can be used to signal build steps, labels would help to distinguish the option set.

2021-03-03 01:09 UTC, CodaFi commented on Tests/SwiftDriverTests/Helpers/IncrementalImportTestFramework.swift
> +extension IncrementalImportTestFramework {
Looks like it's more than helpers here if this is contributing to the type of a protocol requirement.

2021-03-03 01:11 UTC, CodaFi commented on Tests/SwiftDriverTests/Helpers/IncrementalImportTestFramework.swift
> +    assert(mutableSourceFiles.count == 1, "At present, cannot handle more or less than one mutable source")
Perhaps this suggests that we need a cleaner separation between phase-dependent inputs and stable inputs than the enum. Perhaps there could even be a separate requirement.

2021-03-03 01:16 UTC, CodaFi requested changes
I think this framework has the right general structure of a test we'd like here. I do appreciate the explicit phasing here, for example, being a strong part of the interface of the DSL. That said, it is quite terse in certain places (specifying mutations) and quite verbose in others (the number of requirements the client needs to satisfy). It feels like there is a design waiting in the wings here that better utilizes types to bring things those things back into equilibrium. 

tl;dr I think the infrastructure behind the test runner looks good. I think the interface presented to clients could use some work.

2021-03-03 06:39 UTC, davidungar commented
@swift-ci please test macos platform

2021-03-03 07:01 UTC, davidungar commented on Tests/SwiftDriverTests/Helpers/IncrementalImportTestFramework.swift
> + protocol IITF_TestProtocol {
Good idea! Will do.

2021-03-03 07:03 UTC, davidungar commented on Tests/SwiftDriverTests/IncrementalImportTests.swift
> +    case ImportedModule, MainModule
Done!

2021-03-03 07:03 UTC, davidungar commented on Tests/SwiftDriverTests/IncrementalImportTests.swift
> +    case ImportedModule, MainModule
Done.

2021-03-03 23:05 UTC, CodaFi commented
@swift-ci test

2021-03-06 06:03 UTC, davidungar commented
Closing to post a better framework incorporating your feedback

2021-03-06 06:03 UTC, closed without merging