llbuild: model post-compile jobs as a llbuild build rule
apple/swift-driver pull request #528
Opened 2021-03-05 01:07 UTC by nkcsgexi

Instead of piggy-backing on the last compile job for these post-compile jobs,
we should model them as a proper llbuild rule that requests all other compile jobs
as inputs.

2021-03-05 01:07 UTC, nkcsgexi commented
@swift-ci please test

2021-03-05 01:21 UTC, nkcsgexi commented
@swift-ci please test

2021-03-05 01:59 UTC, davidungar requested changes
Adding an all-compile-jobs rule is a fine idea, though as far as I know, things are working fine without it. (Must be something I don't know!)
However, required compilation jobs seem to be getting added to the wrong rule. (See my comments.) And gating the completion of the all-compile-jobs rule might be tricky.

2021-03-05 01:59 UTC, davidungar commented on Sources/SwiftDriverExecution/MultiJobExecutor.swift
>          needInputFor(indices: newJobIndices)
I think that if you leave this in, line 233has to change because the call to `executeAllJobsTaskBuildEngine` in `needInputFor` needs to add the input to your new all-compile-jobs rule.

2021-03-05 02:34 UTC, nkcsgexi commented on Sources/SwiftDriverExecution/MultiJobExecutor.swift
>          needInputFor(indices: newJobIndices)
We definitely need to change this as well, because it's also jobs added asynchronously in `inputsAvailable`.

2021-03-05 02:36 UTC, davidungar commented on Sources/SwiftDriverExecution/MultiJobExecutor.swift
>          needInputFor(indices: newJobIndices)
OK, thanks!

2021-03-10 02:42 UTC, nkcsgexi commented
close this in favor of a more complete fix here: https://github.com/apple/swift-driver/pull/535

2021-03-10 02:42 UTC, closed without merging