[Incremental] ModuleDependencyNode hash caching + bad prior recovery
apple/swift-driver pull request #557
Opened 2021-03-21 06:49 UTC by davidungar

1. Cache the hash of a `ModuleDependencyGraph.Node` in the node.
2. Serialize and deserialize the hash to and from the priors.
3. When a read of the priors fails, stay in incremental mode so as to write a corrected priors.

So far, I've measured on one module with 800 files, this change has cut driver time (when priors are present) by about one third. (Without priors, about 15%). Brings the with-prior time for the new driver down to only 15% more than the old.

2021-03-21 06:49 UTC, davidungar commented
@swift-ci please test

2021-03-21 14:13 UTC, cltnschlosser commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
> +    return h.finalize()
Does it matter that hashes won’t be stable across builds?

2021-03-21 14:13 UTC, cltnschlosser commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +        .fixed(bitWidth: 32),
Can this be one 64 bit value? Or no? Or is there some advantage to this way?

2021-03-21 16:39 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +        .fixed(bitWidth: 32),
It's a limitation of bitstream, which only allocates 5 bits of metadata to hold the length of fixed fields.

2021-03-21 16:40 UTC, CodaFi commented
I measure a similar speedup with the interning patch. Should I land that instead?

2021-03-21 16:42 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
> +    return h.finalize()
It might. @davidungar Suppose a prior graph includes a node that should collide with a newly-created node with identical key material.  The hasher in this case will have a different seed and we may miscompile by scheduling a broken build.

2021-03-21 16:49 UTC, CodaFi requested changes
We cannot serialize an unstable hash.

2021-03-21 17:42 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
> +    return h.finalize()
Great point!

2021-03-21 17:43 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +        .fixed(bitWidth: 32),
As far as I can tell, the serializer requires it to be broken up.

2021-03-21 17:44 UTC, davidungar commented
> We cannot serialize an unstable hash. https://github.com/apple/swift/blob/main/stdlib/public/core/Hasher.swift#L270

Thank you--great point! What we could do, is compute our own hashes, down to the bits.

2021-03-21 17:51 UTC, davidungar commented
Thank you both, @cltnschlosser and @CodaFi . It's really great to get this feedback so quickly. Here's what I'm thinking:
1. I'll do a separate PR with just the read-error recover fix.
2. I'll measure how much benefit there is in this sort of fix, without the serialization of the hash.
3. Let's compare the performance with # 2 with the interning patch. I see plusses and minuses comparing the two.
   -- I can do the experiment, or you can, or better yet, we can each experiment on different projects.

What I saw this this PR and the follow-on was that the new driver, with priors, was within 5% of the old driver. That feels to me like where we need to be. So, we'll want to adopt either something like this, or the interning patch.

2021-03-21 18:04 UTC, cltnschlosser commented
I think no matter what, we want the interning, because it benefits non incremental builds as well.

2021-03-21 19:24 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
> +    return h.finalize()
I have removed the serialization of hashes from this PR.
A quick bake-off looks like this is slightly faster than with the interning patch added to this. And 10% faster than the interning patch alone. But I want to recheck later today. And invite you all to recheck, too!

2021-03-21 19:25 UTC, davidungar commented
@swift-ci please test

2021-03-21 19:26 UTC, davidungar commented
> I think no matter what, we want the interning, because it benefits non incremental builds as well.

It adds a fair bit of complexity. So, I would want to measure the benefit before we take it.

2021-03-21 19:28 UTC, davidungar commented
In https://github.com/apple/swift-driver/pull/557, @cltnschlosser asserts that we ought to take this PR because it will help non-incremental builds, too. Can we get some measurements before we decide?

2021-03-21 19:50 UTC, davidungar commented
@CodaFi Does this version avoid the serialization issue?

2021-03-21 19:53 UTC, davidungar commented
I will be busy for a while this afternoon, but will return to the bake-off later today. I'm not sure I trust my results so far.

2021-03-22 05:34 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
> +    return h.finalize()
OK, but is that 10% across the board or a 10% faster hash? Because it comes at the cost of implementing two deprecated protocol requirements and I don't think it's worth it unless the win is really that big.

2021-03-22 05:53 UTC, CodaFi commented
It avoids the serialization issue, but as-written it's going to add two unsilenceable warnings to the build. If this optimization is worthwhile to take on top of the virtual path amortization, please implement `hashValue` accessors under a different name feed those pre-computed values to `hash(into:)` and document the whole shebang.

2021-03-22 06:10 UTC, davidungar commented
> It avoids the serialization issue, but as-written it's going to add two unsilenceable warnings to the build. If this optimization is worthwhile to take on top of the virtual path amortization, please implement `hashValue` accessors under a different name feed those pre-computed values to `hash(into:)` and document the whole shebang.

Yes, I'll look at that tomorrow. I saw the warnings, but was another 10% of the total time IIRC! I can share more tomorrow.

2021-03-22 15:56 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
> +    return h.finalize()
Yes, 10% across the board. It really is that big, at least in the case I measured.

2021-03-22 15:56 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Node.swift
> +    return h.finalize()
I will explore doing it in a way that doesn't get the warning, as you mentioned elsewhere.

2021-03-22 17:03 UTC, davidungar commented
Closed in favor of https://github.com/apple/swift-driver/pull/561 and https://github.com/apple/swift-driver/pull/547

2021-03-22 17:03 UTC, closed without merging