Use a Confinement Queue to Protect IncrementalCompilationState
apple/swift-driver pull request #565
Opened 2021-03-23 19:12 UTC by CodaFi

This class is serendipitously used only from the main queue for the
Driver's usual use cases. But we have no reason to expect clients of
libSwiftDriver to manipulate this class in the same manner. Provide a serial
confinement queue and protect the mutable members of
IncrementalCompilationState with it.

In the future, we ought to drop the queue and use actors.

rdar://75744005

2021-03-23 19:12 UTC, CodaFi commented
@swift-ci test

2021-03-23 19:27 UTC, cltnschlosser approved these changes

2021-03-23 20:44 UTC, akyrtzi commented
It would be good to consider at some point using a `Lock` wrapper over `pthread_mutex_t`, since in general it can be more efficient than locking via dispatch queue.

2021-03-24 05:18 UTC, BenchR267 approved these changes

2021-03-24 17:32 UTC, davidungar requested changes
Thank you for undertaking this fix. I would like to see two changes:
1. You wrote a nice comment, but I think it could be better. How about something more like what I suggested?
2. More importantly, unless I'm missing something, the synchronization in `getJobs` does not seem to be sufficient. Again, see my inline comments. Do you agree?

2021-03-24 17:32 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +/// The primary form of interaction with the incremental compilation state is
Nice comment! May I offer a suggestion? "The foo is a bar" can usually be strengthened with active voice--who is doing what to whom? Also, here I would be tempted to mention  the first wave, too. Something like:

"When performing an incremental compilation, the driver must determine which source files much be compiled and which may be skipped. This determination is complicated by the fact that one compilation may reveal the need to perform another compilation if, for instance, the user has changed a declaration in one file that another (unchanged) file, depends upon. These decisions are made here."

Then follow up with the "how":

"Additionally the IncrementalCompilationState must account for the batching of compilations into jobs."

And a chronology:

"It starts with the planning process, which creates the jobs for a non-incremental compilation and passes them of to the InitialCompilationState constructor, which builds the ModuleDependencyGraph and initializes two key fields: mandatoryJobsInOrder, and jobsAfterCompiles. The driver will then schedule the mandatory jobs, which are always needed.  This phase is also called the first wave.

Next, as each job finishes, collectJobsDiscoveredToBeNeededAfterFinishing will discover additional jobs that must be run. collectJobsDiscoveredToBeNeededAfterFinishing is also called after each of these jobs. This phase is called the "second wave". When there is no longer any possibility of requiring additional jobs, the driver will run jobsAfterCompiles."

2021-03-24 17:32 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +      .subtracting(job.primaryInputs) // have already compiled these
I think that, instead of protected part of `collectInputsInvalidatedByRunning` and then separately protecting the body of `getJobs`, we need to just protect the whole body of `collectInputsInvalidatedByRunning`. I'm worried about another thread getting in and making changes in between the two synchronizations. In that event, the call to `getJobs` might see a state inconsistent with the rest of collectInputs...

2021-03-24 17:32 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +  private func getJobs(
See above comment. I would protect this in the caller.

2021-03-25 17:15 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +      .subtracting(job.primaryInputs) // have already compiled these
I suppose I don't understand, because the critical section extends to the entire body of this function already...

2021-03-25 17:17 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +      .subtracting(job.primaryInputs) // have already compiled these
Did you mean `collectJobsDiscoveredToBeNeededAfterFinishing`?

2021-03-25 18:15 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +      .subtracting(job.primaryInputs) // have already compiled these
Yes, that's right. Sorry I wrote the wrong thing. Yes the whole of `collectJobsDiscoveredToBeNeededAfterFinishing` needs to be protected.

2021-03-30 16:26 UTC, CodaFi commented
@swift-ci test

2021-03-30 16:43 UTC, davidungar approved these changes
LGTM, thanks!

2021-03-30 16:58 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/IncrementalCompilationState.swift
> +/// The primary form of interaction with the incremental compilation state is
Yes, a document and a pointer is good, but that proposal does not answer my objection:
What bothers me is the general practice if comments that merely summarize the "what" without much, if any, of the "why". The comment, as is, feels like a "what" summary, with very little why. 

Why do we have comments in the code at all? To help future maintainers. The most vital help is that which cannot be understood from reading the code, especially non-local information. I don't mean to single this PR out; many comments I read in the whole llvm/swift-compiler community fail this test.

Sure, what I wrote may feel like a bit much, but as it stands--no such document as you propose exists as of this writing--your comment could be more helpful by adding a little more of the nonobvious, nonlocal information.

However, I won't block the PR for this. I will, however, *unresolve* the conversation.

2021-03-30 17:02 UTC, CodaFi commented
@swift-ci test

2021-03-30 17:51 UTC, CodaFi commented
⛵

2021-03-30 17:51 UTC, merged