[NFC, Incremental] Refactoring to facilitate replacing the inputDependencySourceMap with the right thing
apple/swift-driver pull request #664
Opened 2021-05-14 18:47 UTC by davidungar

A refactoring of `inputDependencySourceMap` prior to really fixing the below:

See https://github.com/apple/swift-driver/pull/662

> There is a remaining lurking bug here that involves an extra step.
Suppose you build in a normal way with foo.swift/foo.c setup. Then you
rebuild and cancel it after a frontend has emitted a new swiftdeps file,
finally, you crash the driver by exploiting this bug. The driver is now
in a state where swiftdeps disagree with the priors which disagree with
the output file map.

> All this to say, we should take the earliest opportunity to remove
BidirectionalMap and its uses. But this commit is not the one to make
such a structural change to the driver.

Start on that.

rdar://77998890

2021-05-14 18:47 UTC, davidungar commented
@swift-ci please test macOS Platform

2021-05-21 20:08 UTC, davidungar commented
@swift-ci please test

2021-05-21 20:16 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +                                               `for` _ : AdditionPurpose) {
Nit: You don't need to quote keywords when they're external labels. If Xcode is highlighting this incorrectly, please file a radar.

2021-05-21 20:20 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +    case mocking,
Please document these. Their names alone don't reveal much at the point of usage.

2021-05-21 20:23 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +    `for` purpose: InputDependencySourceMap.AdditionPurpose
Nit: Same here. Don't need the quotes around `for`.

2021-05-21 20:25 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func enumerateToSerializePriors(
This name conflates the API's purpose with its usage. I think the swift-ier name is something closer to just `enumerate(_:)`.

2021-05-21 20:26 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func getSourceIfKnown(for input: TypedVirtualPath) -> DependencySource? {
Just `source(for:)` would do here.

2021-05-21 20:26 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func getInputIfKnown(for source: DependencySource) -> TypedVirtualPath? {
just `input(for:)` as well

2021-05-21 20:27 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +                                               `for` _ : AdditionPurpose) {
Thanks, will do.

2021-05-21 20:27 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +    case mocking,
Okey-doke!

2021-05-21 20:27 UTC, CodaFi requested changes
Some documentation of this new interface would be welcome. API notes are in-line.

2021-05-21 20:33 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func enumerateToSerializePriors(
The conflation is quite deliberate here. The enclosing type is meant to operate at the level of *intention*. This level distinction paves the way for the greater structural change to come.

2021-05-21 20:38 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func getSourceIfKnown(for input: TypedVirtualPath) -> DependencySource? {
Yes, it would. And I'll remove the "get" prefix.

 The idea here was to draw a very explicit distinction with `ModuleDependencyGraph.getRequiredSource`. In an earlier draft, both were named `getSource` and it was not easy to search for one as opposed to the other, because the only difference in usage was the result type. So, I decided to rename at least one, for the sake of clarity. Then, for the sake of symmetry (and clarity), I renamed them both.
So, I would rather keep the "IfKnown" part.

2021-05-21 20:41 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func getSourceIfKnown(for input: TypedVirtualPath) -> DependencySource? {
Hmm... after eliminating the "get"s, the "IfKnown" etc., moves to the keyword. You'll see after I push. Does that look better?

2021-05-21 20:48 UTC, davidungar commented
> Some documentation of this new interface would be welcome. API notes are in-line.

Yes, I'll add.

2021-05-21 21:04 UTC, davidungar commented
Thanks for the comments; they helped! Have addressed them, and now will fix the conflicts.

2021-05-21 21:09 UTC, davidungar commented
@swift-ci please test

2021-05-21 21:12 UTC, davidungar commented
Thanks, @CodaFi , for productive comments. I've made the changes requested, modulo keeping some intentionality in the function names. This rev may not be there yet, so please let me know what you see.

2021-05-25 17:01 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func enumerateToSerializePriors(
I understand that, but Swift does not use the name of the API in the same way that Objective-C or Smalltalk might encourage the use of intention-revealing selectors.

2021-05-25 17:01 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func input(ifKnownFor source: DependencySource) -> TypedVirtualPath? {
`ifKnownFor` has the same issue as below. Just `for` suffices.

2021-05-25 17:01 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift
> +            graph.inputDependencySourceMap.input(ifKnownFor: source).map {
Any reason this is here? Seems superfluous.

2021-05-25 17:02 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +                                               for why: AdditionPurpose) {
It looks like the `for` parameter is dead. Is that intentional?

2021-05-25 17:05 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +  fileprivate func getDependencySource(
Nit from before: `get` prefixes usually imply indirect return values in Cocoa and Swift. Just `dependencySource(for:diagnosticEngine:)` suffices.

2021-05-25 17:07 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +      else {
Nit: OTBS here please

```suggestion
      if let source = ofm.getDependencySource(for: input, diagnosticEngine: diags) {
         inputDependencySourceMap.addEntry(input, source, for: purpose)
       } else {
```

2021-05-25 17:07 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +  @_spi(Testing) public func source(requiredFor input: TypedVirtualPath,
The `requirement` part of this API is communicated by the type signature being non-optional. You could reinforce this in documentation, but I think `for` suffices.

2021-05-25 17:08 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +      else {
Put this back if you could. This fits onto 80 columns just fine.

2021-05-25 17:14 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +  fileprivate func getDependencySource(
Thanks--done!

2021-05-25 17:15 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +      else {
I did a look-up on "OTBS" and it came back with "off track horse betting"! :)

2021-05-25 17:17 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +      else {
Looks like the request is to put the else on the same line as the closing brace--no prob!

2021-05-25 17:19 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +      else {
What's the rule you follow in general for the "else" in a guard? 80-columns?

2021-05-25 17:19 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +      else {
Will do.

2021-05-25 17:22 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraph.swift
> +  @_spi(Testing) public func source(requiredFor input: TypedVirtualPath,
By putting the requirement in the function name, it becomes more salient at the point of use, *without* clicking to see the documentation, or the type of the assigned-to variable.
Consider: `let foo = source(requiredFor: someInput)` vs `let foo = source(for: someInput)`.
The first construction makes the required nature of the mapping more salient.

2021-05-25 17:25 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +                                               for why: AdditionPurpose) {
Yes. As the documentation says, it will be used in the future. For now, it makes clear at the point-of-use what the purpose is.

2021-05-25 17:29 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/Tracer.swift
> +            graph.inputDependencySourceMap.input(ifKnownFor: source).map {
The "ifKnownFor" is there because it makes two aspects more salient:
1. That the function might not return a value. (In this use, it reinforces that the `map` is to handle an optional, rather than a collection.), and
2. That it depends on if the mapping is "known". I'd be happy to find a better word than "known". "Has been seen" feels too wordy.

2021-05-25 17:32 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/ModuleDependencyGraphParts/InputDependencySourceMap.swift
> +  @_spi(Testing) public func input(ifKnownFor source: DependencySource) -> TypedVirtualPath? {
Please see my comment for the next issue. I have a rule: Correlate salience with importance in order to ease the comprehension for new maintainer.

2021-05-25 17:41 UTC, davidungar commented
@CodaFi Thank you for your review. I have responded to your comments and made changes where I agree. You have a wealth of experience with Swift style, and that helps my code fit in. To clarify, I think we agree that this PR makes no functional change, and that (for me) is the most critical part of your review, because I don't want to break the driver. There are some remaining disagreements on function naming, but I think they follow from my practice of choosing salience at the point-of-use. If Xcode were better at showing inferred types, or Doxygen documentation, I'd be in agreement with you. 

Would you be able to approve this PR at this point?

2021-05-25 17:43 UTC, davidungar commented
@swift-ci please test

2021-05-27 18:30 UTC, CodaFi approved these changes
I remain unconvinced that this is a meaningful change, and moreover that the new API surface here is an improvement over the status quo. But this PR has also been blocked on my review and I don’t see a reason for that much, so

2021-05-27 18:31 UTC, davidungar commented
> I remain unconvinced that this is a meaningful change, and moreover that the new API surface here is an improvement over the status quo. But this PR has also been blocked on my review and I don’t see a reason for that much, so

I understand. Thank you so very much for compromising here.

2021-05-27 18:31 UTC, merged