[DNM] Add input addition test and fix nondeterminism bug
apple/swift-driver pull request #687
Opened 2021-05-28 23:43 UTC by davidungar

Do not merge until https://github.com/apple/swift-driver/pull/686 is merged. 
This PR adds a test to test input additions and fixes a bug that can manifest in nondeterministic outputs from `-driver-show-incremental`.

2021-05-28 23:43 UTC, davidungar commented
@swift-ci please test

2021-06-01 21:55 UTC, davidungar commented
@swift-ci please test

2021-06-01 23:29 UTC, artemcm approved these changes

2021-06-01 23:34 UTC, CodaFi requested changes
(whoops, read the wrong variable there)

2021-06-01 23:35 UTC, CodaFi approved these changes

2021-06-01 23:36 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
>    private func sortByCommandLineOrder(_ inputs: Set<TypedVirtualPath>) -> [TypedVirtualPath] {
This function can be removed and replaced by a `where` clause on the appropriate loops. This will avoid re-materializing the inputs into a separate collection.

2021-06-02 00:04 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
>    private func sortByCommandLineOrder(_ inputs: Set<TypedVirtualPath>) -> [TypedVirtualPath] {
@CodaFi Thank you very much for a quick review and your approval despite this comment.
I am reluctant to perform the optimization you suggest because:
1. Factoring the functionality out allows it to possess a descriptive name, and
2. It is called only when `-driver-show-incremental`  is used. Thus, it would not affect performance in normal use-cases.

Would there be any way to preserve the factoring and gain the optimization, too?
For example, suppose the loop with `where` clause were in the function and it took a closure parameter?
Would that be more efficient? How would the cost of the closure compare with the cost of materializing the resultant collection?

I'd be happy to do a future PR if both goals could be met. And thanks again, for your help here.

2021-06-02 00:04 UTC, merged

2021-06-02 00:06 UTC, davidungar commented
Thank you, @artemcm and @CodaFi !

2021-06-02 00:20 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
>    private func sortByCommandLineOrder(_ inputs: Set<TypedVirtualPath>) -> [TypedVirtualPath] {
> Would there be any way to preserve the factoring and gain the optimization, too?

Somebody has to have a loop with a where clause somewhere. This method could be transformed to take a non-escaping closure and turned into an iterator. After optimization, it should be equivalent to the loop+where clause form since its body should be quite profitable from the inliner's point of view.

2021-06-02 00:21 UTC, CodaFi commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
>    private func sortByCommandLineOrder(_ inputs: Set<TypedVirtualPath>) -> [TypedVirtualPath] {
You can also return a `LazyFilterSequence` here.

2021-06-11 18:40 UTC, davidungar commented
rdar://77998890