Disable output file map diagnostic for non-incremental mode
apple/swift-driver pull request #707
Opened 2021-06-10 04:20 UTC by keith

This re-implements this logic https://github.com/apple/swift/blob/3116eed2e465a2688f070b3b87adc106cbbaf09f/lib/Driver/Driver.cpp#L414-L417 to not warn when output file maps don't have a main entry when using WMO

2021-06-10 12:51 UTC, brentleyjones approved these changes

2021-06-30 21:58 UTC, davidungar requested changes
Thank you for doing this. It looks good, but before merging I'd like to see an XCTest added to check this. It might be easiest to add a test in `IncrementalCompilationTests.swift`, in which the test runs the driver both with- and without the `-incremental` flag and checks to see whether the diagnostic is emitted when appropriate.

Would you like to add such a test?

2021-08-03 21:02 UTC, brentleyjones commented
FYI, this is still an issue in Xcode 13.0 beta 4.

2021-08-05 01:40 UTC, keith commented
Updated with tests!

2021-08-05 17:14 UTC, artemcm commented
@swift-ci please test

2021-08-05 17:30 UTC, artemcm approved these changes

2021-08-05 17:31 UTC, artemcm commented
@davidungar could you please take another look? It looks good to go to me.

2021-08-16 17:38 UTC, keith commented
@davidungar mind taking another look here?

2021-08-23 18:35 UTC, keith commented
@davidungar mind taking another look here?

2021-09-09 15:39 UTC, davidungar approved these changes
Sorry this PR slipped under my radar. Thanks to @CodaFi for pinging me. In future, please feel free to ping me directly. 
It would be great if you could add a comment somewhere (if it's not already there) explaining why one would want to exclude the main entry, or under what circumstances. Otherwise, LGTM and thank you for your patience!

2021-09-09 15:39 UTC, davidungar commented on Tests/TestUtilities/OutputFileMapCreator.swift
> +  private let excludeMainEntry: Bool
Would it be possible to add a comment somewhere explaining when you would want to exclude the main entry?

2021-09-09 15:44 UTC, keith commented
Done, thanks for following up. To be clear where do you mean when you say "ping you directly"?

2021-09-09 16:08 UTC, artemcm approved these changes

2021-09-09 16:08 UTC, artemcm commented
@swift-ci please test

2021-09-09 16:15 UTC, brentleyjones commented
@artemcm Is this able to get CP'ed into 5.5?

2021-09-09 16:25 UTC, artemcm commented
> @artemcm Is this able to get CP'ed into 5.5?

Yeah, I think this change is pretty safe.
Please create a cherry-pick PR against `release/5.5` and use something like https://github.com/apple/swift/pull/39140 as a template for the PR description.

2021-09-09 16:25 UTC, merged

2021-09-09 17:17 UTC, keith commented
Thanks! Submitted https://github.com/apple/swift-driver/pull/828 for the CP