[SIL] Simplify debug info generation flow for SIL files
apple/swift-driver pull request #737
Opened 2021-06-29 22:43 UTC by mshockwave

- Now `-g` implies `-Xllvm -sil-print-debuginfo` if the output file
  format is SIL.
- The `-gsil` is renamed into `-sil-based-debuginfo` to avoid confusing that flag -- which supposes to describe the source of debug info -- with `-g`, `-gnone`, `-gline-tables-only` etc -- which dictates the level of debug information.

This PR is a synergy with https://github.com/apple/swift/pull/38167.

2021-06-29 22:47 UTC, mshockwave commented
@swift-ci test

2021-06-29 22:54 UTC, nkcsgexi requested changes

2021-06-29 22:54 UTC, nkcsgexi commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> +        commandLine.appendFlag("-sil-print-debuginfo")
You should be able to use `.Xllvm` and `.debugOnSil` here.

2021-06-29 22:54 UTC, nkcsgexi commented on Sources/SwiftOptions/Options.swift
> +  public static let debugOnSil: Option = Option("-sil-based-debuginfo", .flag, attributes: [.helpHidden, .frontend, .noDriver], helpText: "Write the SIL into a file and generate debug-info to debug o
We usually don't rename an argument unless it's really appealing, so that driver is always in compatible with the compiler.

2021-06-29 22:58 UTC, adrian-prantl approved these changes
LGTM form my side, but please wait for @nkcsgexi to also approve the PR.

2021-06-29 22:58 UTC, adrian-prantl commented on Sources/SwiftOptions/Options.swift
> +  public static let debugOnSil: Option = Option("-sil-based-debuginfo", .flag, attributes: [.helpHidden, .frontend, .noDriver], helpText: "Write the SIL into a file and generate debug-info to debug o
In this case, I think we do want to rename the option. The problem is that `-gsil` invades in the `-g` option namespace and thus can't be combined with the other `-g{0,line-tables-only,dwarf-types,{}}` options. The option is used only by a handful of Swift compiler developers.

2021-06-29 23:00 UTC, adrian-prantl commented
We may have an exhaustive list of the existing `-gsil` userbase in the list of Reviewers now 😀

2021-06-29 23:02 UTC, nkcsgexi commented on Sources/SwiftOptions/Options.swift
> +  public static let debugOnSil: Option = Option("-sil-based-debuginfo", .flag, attributes: [.helpHidden, .frontend, .noDriver], helpText: "Write the SIL into a file and generate debug-info to debug o
ah, OK. Thanks for the explanation! Another question: is `Options.swift` updated using the steps mentioned [here](https://github.com/apple/swift-driver#rebuilding-optionsswift)?

2021-06-29 23:05 UTC, mshockwave commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> +        commandLine.appendFlag("-sil-print-debuginfo")
I'm changing "-Xllvm" to `.Xllvm` but "-sil-print-debuginfo" doesn't have any corresponding enum (`.debugOnSil` is mapped to "-sil-based-debuginfo").

2021-06-29 23:06 UTC, atrick approved these changes
Sweet!

2021-06-29 23:07 UTC, mshockwave commented on Sources/SwiftOptions/Options.swift
> +  public static let debugOnSil: Option = Option("-sil-based-debuginfo", .flag, attributes: [.helpHidden, .frontend, .noDriver], helpText: "Write the SIL into a file and generate debug-info to debug o
> ah, OK. Thanks for the explanation! Another question: is Options.swift updated using the steps mentioned here?
Currently not, I'm going to update it using that method (and update the PR here is there is any difference). Thanks for the pointer

2021-06-29 23:08 UTC, adrian-prantl commented
@mshockwave For the odd chance that there are other users of `-gsil`: Since we don't use `-gsil` for anything else — should we define it and print a "this option is deprecated" error or alias it to the new option?

2021-06-29 23:10 UTC, mshockwave commented
> @mshockwave For the odd chance that there are other users of `-gsil`: Since we don't use `-gsil` for anything else — should we define it and print a "this option is deprecated" error or alias it to the new option?

Yes I can do that

2021-06-29 23:11 UTC, atrick commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> +        commandLine.appendFlag("-sil-print-debuginfo")
I'm curious, why this is in the driver and not the frontend? Don't we want `swift-frontend -g -emit-sil` to do the right thing? I generally expect the driver and frontend flags to have the same meaning.

2021-06-29 23:17 UTC, adrian-prantl commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> +        commandLine.appendFlag("-sil-print-debuginfo")
I think I asked a similar question in https://github.com/apple/swift-driver/pull/737 — I think it would make sense to update the frontend flags in a similar manner (and a separate patch).

2021-06-29 23:19 UTC, atrick commented on Sources/SwiftDriver/Jobs/FrontendJobHelpers.swift
> +        commandLine.appendFlag("-sil-print-debuginfo")
That's great if we add -g `.sil` handling for the frontend in a separate patch. I'm just not sure why we need to add a `-Xllvm` flag to the frontend invocation if the frontend already does the right thing.

2021-06-30 00:25 UTC, mshockwave commented
> > @mshockwave For the odd chance that there are other users of `-gsil`: Since we don't use `-gsil` for anything else — should we define it and print a "this option is deprecated" error or alias it to the new option?
> 
> Yes I can do that

Please refer to https://github.com/apple/swift/pull/38167#issuecomment-871006641

@swift-ci test

2021-06-30 01:43 UTC, nkcsgexi approved these changes
LGTM!

2021-06-30 01:46 UTC, nkcsgexi commented
The patch looks great to me! For future reference, we don't have to update the option list if the driver code doesn't use any new options in the implementation. The option list will be eventually updated by later changes.

2021-06-30 20:23 UTC, merged