SwiftDriver: initial (incomplete) windows port
apple/swift-driver pull request #878
Opened 2021-10-15 15:56 UTC by compnerd

This is sufficient to build on Windows, and the resulting driver is able
to somewhat function.  The tests are still not usable due to assumptions
about path which do not hold and the insufficiency of the path
representation in tools-support-core.  This is likely best approached by
replacing the use of `Path` from t-s-c with the representation in
system.  However, this allows some attempt to validate the swift-driver
which is increasingly becoming required for s-p-m, and thus unblocks
further work.

2021-10-15 15:59 UTC, compnerd commented
@artemcm - the big problem with this change is that there are a few places where I cannot reliably make a distinction for the executable names (i.e. extensions - `.exe`).  Do you have thoughts on how to handle this?  I'm leaning towards adding a freestanding function:

```swift
func executable(_ name: String) -> String {
#if os(Windows)
  guard name.suffix(from: name.index(name.endIndex, offsetBy: -4))) == ".exe" else {
    return "\(name).exe"
  }
  return name
#else
  return name
#endif
}
```

2021-10-17 18:06 UTC, compnerd commented
@swift-ci please test Darwin platform

2021-10-17 18:06 UTC, compnerd commented
@swift-ci please test macOS platform

2021-10-18 22:27 UTC, compnerd commented
> > @artemcm - the big problem with this change is that there are a few places where I cannot reliably make a distinction for the executable names (i.e. extensions - `.exe`). Do you have thoughts on how to handle this? I'm leaning towards adding a freestanding function:
> > ```swift
> > func executable(_ name: String) -> String {
> > #if os(Windows)
> >   guard name.suffix(from: name.index(name.endIndex, offsetBy: -4))) == ".exe" else {
> >     return "\(name).exe"
> >   }
> >   return name
> > #else
> >   return name
> > #endif
> > }
> > ```
> 
> I think this is an entirely reasonable approach.

Okay; just wanted to make sure that someone doesn't have a better idea (I can propose and implement and still dislike my idea right? :-D).  There is some duplication - I'm like to move the function to a different file if I could get a bit of guidance as to where such a utility function should reside.

2021-10-18 23:24 UTC, cltnschlosser reviewed
For the most part looks good, obviously lots of TODOs/FIXMEs for the future.

BTW is there a good "Beginners guide to Swift on Windows"?

2021-10-18 23:24 UTC, cltnschlosser commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +      // To do this we need access to the Driver as we can check Driver.hostTriple.isWindows
Not pretty, but `self is WindowsToolchain`

2021-10-18 23:24 UTC, cltnschlosser commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +      .replacingOccurrences(of: ".", with: "_")
Yeah, I guess it would be nice if the environment variables were consistent across platforms. So windows doesn't always have an extra `_EXE` in its variables.

2021-10-18 23:24 UTC, cltnschlosser commented on Sources/SwiftDriver/Driver/Driver.swift
> +}
Could make a WindowsExtensions.swift or something and make this internal so it doesn't need to be duplicated.

2021-10-18 23:24 UTC, cltnschlosser commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +    getEnvSearchPaths(pathString: ProcessEnv.path, currentWorkingDirectory: fileSystem.currentWorkingDirectory)
Does this break tests or something? Where an (arbitrary) env might have been injected in.

2021-10-18 23:24 UTC, cltnschlosser commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      let os: String = target.os?.rawValue ?? "none"
You can probably capitalize the rawValue of this enum for Windows.

Is "none" a better value than just returning nil here?

2021-10-18 23:36 UTC, compnerd commented on Sources/SwiftDriver/Driver/Driver.swift
> +}
That works for me!

2021-10-18 23:36 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +    getEnvSearchPaths(pathString: ProcessEnv.path, currentWorkingDirectory: fileSystem.currentWorkingDirectory)
Yeah, it was breaking both tests as well as use of the driver.

2021-10-18 23:41 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/WindowsToolchain.swift
> +      let os: String = target.os?.rawValue ?? "none"
Ah, I think I see what you are proposing. I think that the returning `nil` actually could work and be better.  I'll make that change. The capitalization though I don't know how to handle :-(.

2021-10-19 23:18 UTC, artemcm requested changes
I have just one concern about the Toolchain's use of environment variables, but other than that this is great!

2021-10-19 23:18 UTC, artemcm commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +    getEnvSearchPaths(pathString: ProcessEnv.path, currentWorkingDirectory: fileSystem.currentWorkingDirectory)
I'm not convinced this won't potentially break downstream driver clients. `Toolchain.env` comes all the way from a `Driver.init` argument, which defaults to `ProcessEnv.vars`, but can also be invoked with a custom environment when the driver is used as a library.

Can we instead continue using `env` and disambiguate `"Path"` or `"PATH"` based on the platform like [TSC does](https://github.com/apple/swift-tools-support-core/blob/main/Sources/TSCBasic/ProcessEnv.swift#L61)?

2021-10-19 23:18 UTC, artemcm commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +      // TODO(compnerd) correct this for Windows - %SystemDrive%\Developer\Toolchains\....xctoolchain\usr\bin
I think this comment is now stale?

2021-10-20 00:31 UTC, compnerd commented on Sources/SwiftDriver/Driver/WindowsExtensions.swift
> +internal func exe(_ name: String) -> String {
I'm fine with `executableName`.  I originally tried `executable` but ran into a conflict.

2021-10-20 00:32 UTC, compnerd commented on Sources/SwiftDriver/Toolchains/Toolchain.swift
> +      // TODO(compnerd) correct this for Windows - %SystemDrive%\Developer\Toolchains\....xctoolchain\usr\bin
Oh, right, it is.

2021-10-21 04:36 UTC, merged