[Incremental Builds] Skip `jobsBeforeCompiles` if no compilation jobs are to be run.
apple/swift-driver pull request #914
Opened 2021-11-19 21:58 UTC by artemcm

Otherwise, for example, when using the `emit-module-separately` mode, the `emit-module` job is *always* mandatory, even on a null build.

Resolves rdar://85554508

2021-11-19 21:58 UTC, artemcm commented
@swift-ci please test

2021-11-19 22:20 UTC, davidungar requested changes
My worry is that there may be post-compile jobs depending upon the pre-compile jobs, even if there are no compilations. Is there some sort of check that could be added somewhere, or if it already exists elsewhere then point to it from the new logic?
Otherwise, it's fine.

2021-11-19 22:20 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
> +                                                                     batchedCompilationJobs
Two thoughts:
1. a comment explaining the "why" would be good
2. I like the use of the ?:
3. What if there are post-compilation jobs? Might the pre-compilation jobs still be needed then? Should there be an assert ensuring no post-compilation jobs? Or a check?
4. I guess that was more than two thoughts.

2021-11-19 23:45 UTC, artemcm commented
@swift-ci please test

2021-11-19 23:46 UTC, artemcm commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
> +                                                                     batchedCompilationJobs
Thanks for the comments @davidungar!
Post-compile job dependences is a valid concern that I didn't think of.  

I've added a check to make sure `beforeCompiles` jobs do not produce any such dependencies to make sure, before we decide to not run them.

2021-11-20 02:35 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
> +                                                                     batchedCompilationJobs
Great, thank you. I'll take a look.

2021-11-20 02:43 UTC, davidungar commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
> +    return !beforeCompileJobOutputs.intersection(afterCompileJobInputs).isEmpty
Looks good. If you need an optimization, you could redo the previous three lines:
```
return jobsInPhases.afterCompiles.contains {postCompileJob in
  postCompileJob.inputs.contains(beforeCompileJobOutputs.contains)}
```
I'm not sure which is the best order for the iteration, but the key idea would be to stop looking as soon as the first intersection is found.
Just something to consider.

2021-11-20 02:46 UTC, davidungar approved these changes
Thanks, certainly above threshold now. Two thoughts you could consider:
1. The `afterCompileJobsDependOnBeforeCompileJobs` routine could be written to be faster, at the cost of some clarity. I don't know what the right tradeoff is, but consider projects with lots of .o files.
2. AFAICT, you didn't add a test to ensure that the aforementioned code is working. Again, not critical, IMO. Just a thought.

But it's fine to land as-is.

2021-11-30 17:14 UTC, artemcm commented
@swift-ci please test

2021-11-30 17:15 UTC, artemcm commented on Sources/SwiftDriver/IncrementalCompilation/FirstWaveComputer.swift
> +    return !beforeCompileJobOutputs.intersection(afterCompileJobInputs).isEmpty
I like your suggestion and don't think it sacrifices much clarity. Thank you.

2021-11-30 19:42 UTC, merged