Only emit ABI descriptors when Library Evolution is enabled
apple/swift-driver pull request #995
Opened 2022-01-26 23:36 UTC by artemcm

These descriptors are not otherwise meaningful so this avoid unnecessary work when we do not require it.

2022-01-26 23:36 UTC, artemcm commented
@swift-ci please test

2022-01-27 00:20 UTC, xymus approved these changes
Looks good!

2022-01-27 19:13 UTC, nkcsgexi requested changes
Discussed with Artem about this offline, we plan to still emit the abi descriptor for non-library-evolution modules because it's an extensible format which may carry other semantic information for other purposes. 

Instead, we decided to drop ABI descriptor emission for non-Darwin platforms.

2022-01-27 20:25 UTC, artemcm commented
Closing in favour of https://github.com/apple/swift-driver/pull/998

2022-01-27 20:25 UTC, closed without merging